[package]
name = "spb-serial-data-receiver"
version = "0.1.0"
authors = ["ZhangYi <zhangyi@goldensecure.com>"]
edition = "2018"

[dependencies]
serialport = { version = "~3.2", default-features = false }
clap = "2.31"
crossbeam-channel = "0.3"
rumqtt = "0.30"

